version: '3.8'

services:
  database:
    image: mongo:7.0.5
    container_name: prosper-guard-database
    restart: always
    ports:
      - 3060:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - prosper-guard-backend
    volumes:
      - prosper-guard-database:/data/db

  server:
    build:
      context: ./applications/server/
      dockerfile: dev.dockerfile
    container_name: prosper-guard-server
    restart: always
    ports:
      - 3070:${BACKEND_PORT}
    environment:
      PORT: ${BACKEND_PORT}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - prosper-guard-backend
      - prosper-guard-frontend
    volumes:
      - ./applications/server/:/app
    depends_on:
      - database

  web-client:
    build:
      context: ./applications/web-client/
      dockerfile: dev.dockerfile
    container_name: prosper-guard-web-client
    restart: always
    networks:
      - prosper-guard-frontend
    ports:
      - 3080:8080
    volumes:
      - ./applications/web-client:/app
    depends_on:
      - server

networks:
  prosper-guard-frontend:
  prosper-guard-backend:

volumes:
  prosper-guard-database:
