version: '3.8'

services:
  database:
    image: postgres:16.1-alpine3.19
    container_name: prosper-guard-database
    restart: always
    ports:
      - 3060:5432
    environment:
      POSTGRES_USER: ${MONGO_INITDB_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      POSTGRES_DB: 'ProsperGuard'
    networks:
      - prosper-guard-backend
    volumes:
      - prosper-guard-database:/var/lib/postgresql

  server:
    build:
      context: ./applications/server/
      dockerfile: dev.dockerfile
    container_name: prosper-guard-server
    restart: always
    ports:
      - 3070:${BACKEND_PORT}
    environment:
      PORT: ${BACKEND_PORT}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - prosper-guard-backend
      - prosper-guard-frontend
    volumes:
      - ./applications/server/:/app
    depends_on:
      - database

  web-client:
    build:
      context: ./applications/web-client/
      dockerfile: dev.dockerfile
    container_name: prosper-guard-web-client
    restart: always
    networks:
      - prosper-guard-frontend
    ports:
      - 3080:8080
    volumes:
      - ./applications/web-client:/app
    depends_on:
      - server

networks:
  prosper-guard-frontend:
  prosper-guard-backend:

volumes:
  prosper-guard-database:
