version: '3.1'

services:
  web-client:
    build:
      context: ./applications/web-client/
      dockerfile: dev.dockerfile
    container_name: prosper-guard-web-client
    restart: always
    networks:
      - frontend
    ports:
      - 3080:8080
    volumes:
      - ./applications/web-client:/app

  database:
    env_file:
      - .env.dev
    image: mongo:7.0.5
    container_name: database
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=$${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - database:/data/db

networks:
  frontend:
  backend:

volumes:
  database:
