version: '3.8'

services:
  web-client:
    build:
      context: ./applications/web-client/
      dockerfile: dev.dockerfile
    container_name: prosper-guard-web-client
    restart: always
    networks:
      - frontend
    ports:
      - 8080:8080
    volumes:
      - ./applications/web-client:/app

networks:
  frontend:
  backend:

volumes:
  database: