// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
