type User {
  id: ID!
  name: String!
  email: String!
  passwordHash: String!
  createdAt: String!
  updatedAt: String!
}

type Query {
  users: [User!]!
}

input CreateNewUser {
  name: String!
  email: String!
  password: String!
}

type Mutation {
  createUser(input: CreateNewUser!): User!
}
